//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomelo.AspNetCore.WebPages.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChartTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ChartTemplates() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomelo.AspNetCore.WebPages.Properties.ChartTemplates", typeof(ChartTemplates).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与  &lt;Chart BackColor=&quot;#D3DFF0&quot; BackGradientStyle=&quot;TopBottom&quot; BackSecondaryColor=&quot;White&quot; BorderColor=&quot;26, 59, 105&quot; BorderlineDashStyle=&quot;Solid&quot; BorderWidth=&quot;2&quot; Palette=&quot;BrightPastel&quot;&gt;
        /// 	&lt;ChartAreas&gt;
        ///		&lt;ChartArea Name=&quot;Default&quot; _Template_=&quot;All&quot; BackColor=&quot;64, 165, 191, 228&quot; BackGradientStyle=&quot;TopBottom&quot; BackSecondaryColor=&quot;White&quot; BorderColor=&quot;64, 64, 64, 64&quot; BorderDashStyle=&quot;Solid&quot; ShadowColor=&quot;Transparent&quot; /&gt; 
        ///	&lt;/ChartAreas&gt;
        ///	&lt;Legends&gt;
        ///		&lt;Legend _Template_=&quot;All&quot; BackColor=&quot;Transparent&quot; Font=&quot;Trebuchet MS, 8.25pt, [字符串的其余部分被截断]”； 类似的本地化字符串。
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与  &lt;Chart BackColor=&quot;#C9DC87&quot; BackGradientStyle=&quot;TopBottom&quot; BorderColor=&quot;181, 64, 1&quot; BorderWidth=&quot;2&quot; BorderlineDashStyle=&quot;Solid&quot; Palette=&quot;BrightPastel&quot;&gt;
        ///  &lt;ChartAreas&gt;
        ///    &lt;ChartArea Name=&quot;Default&quot; _Template_=&quot;All&quot; BackColor=&quot;Transparent&quot; BackSecondaryColor=&quot;White&quot; BorderColor=&quot;64, 64, 64, 64&quot; BorderDashStyle=&quot;Solid&quot; ShadowColor=&quot;Transparent&quot;&gt;
        ///      &lt;AxisY LineColor=&quot;64, 64, 64, 64&quot;&gt;
        ///        &lt;MajorGrid Interval=&quot;Auto&quot; LineColor=&quot;64, 64, 64, 64&quot; /&gt;
        ///        &lt;LabelStyle Font=&quot;Trebuchet MS, 8.25pt, style=Bold&quot; /&gt;
        /// [字符串的其余部分被截断]”； 类似的本地化字符串。
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 &lt;Chart Palette=&quot;SemiTransparent&quot; BorderColor=&quot;#000&quot; BorderWidth=&quot;2&quot; BorderlineDashStyle=&quot;Solid&quot;&gt;
        ///&lt;ChartAreas&gt;
        ///    &lt;ChartArea _Template_=&quot;All&quot; Name=&quot;Default&quot;&gt;
        ///            &lt;AxisX&gt;
        ///                &lt;MinorGrid Enabled=&quot;False&quot; /&gt;
        ///                &lt;MajorGrid Enabled=&quot;False&quot; /&gt;
        ///            &lt;/AxisX&gt;
        ///            &lt;AxisY&gt;
        ///                &lt;MajorGrid Enabled=&quot;False&quot; /&gt;
        ///                &lt;MinorGrid Enabled=&quot;False&quot; /&gt;
        ///            &lt;/AxisY&gt;
        ///    &lt;/ChartArea&gt;
        ///&lt;/ChartAreas&gt;
        ///&lt;/Chart&gt; 类似的本地化字符串。
        /// </summary>
        public static string Vanilla {
            get {
                return ResourceManager.GetString("Vanilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与  &lt;Chart BackColor=&quot;#555&quot; BackGradientStyle=&quot;TopBottom&quot; BorderColor=&quot;181, 64, 1&quot; BorderWidth=&quot;2&quot; BorderlineDashStyle=&quot;Solid&quot; Palette=&quot;SemiTransparent&quot; AntiAliasing=&quot;All&quot;&gt;
        ///    &lt;ChartAreas&gt;
        ///        &lt;ChartArea Name=&quot;Default&quot; _Template_=&quot;All&quot; BackColor=&quot;Transparent&quot; BackSecondaryColor=&quot;White&quot; BorderColor=&quot;64, 64, 64, 64&quot; BorderDashStyle=&quot;Solid&quot; ShadowColor=&quot;Transparent&quot;&gt;
        ///            &lt;Area3DStyle LightStyle=&quot;Simplistic&quot; Enable3D=&quot;True&quot; Inclination=&quot;30&quot; IsClustered=&quot;False&quot; IsRightAngleAxes=&quot;False&quot; Perspective=&quot;10&quot;  [字符串的其余部分被截断]”； 类似的本地化字符串。
        /// </summary>
        public static string Vanilla3D {
            get {
                return ResourceManager.GetString("Vanilla3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与  &lt;Chart  BackColor=&quot;#FADA5E&quot; BackGradientStyle=&quot;TopBottom&quot; BorderColor=&quot;#B8860B&quot; BorderWidth=&quot;2&quot; BorderlineDashStyle=&quot;Solid&quot; Palette=&quot;EarthTones&quot;&gt;
        ///  &lt;ChartAreas&gt;
        ///    &lt;ChartArea Name=&quot;Default&quot; _Template_=&quot;All&quot; BackColor=&quot;Transparent&quot; BackSecondaryColor=&quot;White&quot; BorderColor=&quot;64, 64, 64, 64&quot; BorderDashStyle=&quot;Solid&quot; ShadowColor=&quot;Transparent&quot;&gt;
        ///      &lt;AxisY&gt;
        ///        &lt;LabelStyle Font=&quot;Trebuchet MS, 8.25pt, style=Bold&quot; /&gt;
        ///      &lt;/AxisY&gt;
        ///      &lt;AxisX LineColor=&quot;64, 64, 64, 64&quot;&gt;
        ///        &lt;LabelStyle Font=&quot;Trebuchet MS,  [字符串的其余部分被截断]”； 类似的本地化字符串。
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
