//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomelo.AspNetCore.WebPages.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    强类型资源类，用于查找本地化字符串，等等。
    /// </summary>
    // 此类已由 StronglyTypedResourceBuilder 自动生成
    // 通过 ResGen 或 Visual Studio 之类的工具提供的类。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (使用 /str 选项)，或重新生成 VS 项目。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HelpersResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal HelpersResources() {
        }
        
        /// <summary>
        ///    返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pomelo.AspNetCore.WebPages.Properties.HelpersResources", typeof(HelpersResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    重写所有项的当前线程的 CurrentUICulture 属性
        ///    使用此强类型资源类进行资源查找。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    查找与 Argument conversion to type &quot;{0}&quot; failed. 类似的本地化字符串。
        /// </summary>
        public static string Chart_ArgumentConversionFailed {
            get {
                return ResourceManager.GetString("Chart_ArgumentConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 A series cannot be data-bound to a string object. 类似的本地化字符串。
        /// </summary>
        public static string Chart_ExceptionDataBindSeriesToString {
            get {
                return ResourceManager.GetString("Chart_ExceptionDataBindSeriesToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The theme file &quot;{0}&quot; could not be found. 类似的本地化字符串。
        /// </summary>
        public static string Chart_ThemeFileNotFound {
            get {
                return ResourceManager.GetString("Chart_ThemeFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The hash algorithm &apos;{0}&apos; is not supported, valid values are: sha256, sha1, md5 类似的本地化字符串。
        /// </summary>
        public static string Crypto_NotSupportedHashAlg {
            get {
                return ResourceManager.GetString("Crypto_NotSupportedHashAlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 &quot;{0}&quot; is invalid image format. Valid values are image format names like: &quot;JPEG&quot;, &quot;BMP&quot;, &quot;GIF&quot;, &quot;PNG&quot;, etc. 类似的本地化字符串。
        /// </summary>
        public static string Image_IncorrectImageFormat {
            get {
                return ResourceManager.GetString("Image_IncorrectImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Unable to convert to &quot;{0}&quot;. Use Json.Decode&lt;T&gt; instead. 类似的本地化字符串。
        /// </summary>
        public static string Json_UnableToConvertType {
            get {
                return ResourceManager.GetString("Json_UnableToConvertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Previously Displayed 类似的本地化字符串。
        /// </summary>
        public static string ObjectInfo_PreviousDisplayed {
            get {
                return ResourceManager.GetString("ObjectInfo_PreviousDisplayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Accessing a property threw an exception:  类似的本地化字符串。
        /// </summary>
        public static string ObjectInfo_PropertyThrewException {
            get {
                return ResourceManager.GetString("ObjectInfo_PropertyThrewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 File path &quot;{0}&quot; is invalid. 类似的本地化字符串。
        /// </summary>
        public static string PathUtils_IncorrectPath {
            get {
                return ResourceManager.GetString("PathUtils_IncorrectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Additional server information is available when the page is running with high trust. 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_AdditionalInfo {
            get {
                return ResourceManager.GetString("ServerInfo_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Environment Variables 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_EnvVars {
            get {
                return ResourceManager.GetString("ServerInfo_EnvVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 ASP.NET Server Information 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_Header {
            get {
                return ResourceManager.GetString("ServerInfo_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 HTTP Runtime Information 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_HttpRuntime {
            get {
                return ResourceManager.GetString("ServerInfo_HttpRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Legacy Code Access Security 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_LegacyCAS {
            get {
                return ResourceManager.GetString("ServerInfo_LegacyCAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Legacy Code Access Security has been detected on your system. Microsoft WebPage features require the ASP.NET 4 Code Access Security model. For information about how to resolve this, contact your server administrator. 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_LegacyCasHelpInfo {
            get {
                return ResourceManager.GetString("ServerInfo_LegacyCasHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 no value 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_NoValue {
            get {
                return ResourceManager.GetString("ServerInfo_NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Server Configuration 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_ServerConfigTable {
            get {
                return ResourceManager.GetString("ServerInfo_ServerConfigTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 ASP.NET Server Variables 类似的本地化字符串。
        /// </summary>
        public static string ServerInfo_ServerVars {
            get {
                return ResourceManager.GetString("ServerInfo_ServerVars", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The column name cannot be null or an empty string unless a custom format is specified. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_ColumnNameOrFormatRequired {
            get {
                return ResourceManager.GetString("WebGrid_ColumnNameOrFormatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Column &quot;{0}&quot; does not exist. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_ColumnNotFound {
            get {
                return ResourceManager.GetString("WebGrid_ColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The WebGrid instance is already bound to a data source. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_DataSourceBound {
            get {
                return ResourceManager.GetString("WebGrid_DataSourceBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 A data source must be bound before this operation can be performed. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_NoDataSourceBound {
            get {
                return ResourceManager.GetString("WebGrid_NoDataSourceBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 This operation is not supported when paging is disabled for the &quot;WebGrid&quot; object. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_NotSupportedIfPagingIsDisabled {
            get {
                return ResourceManager.GetString("WebGrid_NotSupportedIfPagingIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 This operation is not supported when sorting is disabled for the &quot;WebGrid&quot; object. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_NotSupportedIfSortingIsDisabled {
            get {
                return ResourceManager.GetString("WebGrid_NotSupportedIfSortingIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 To use this argument, pager mode &quot;{0}&quot; must be enabled. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_PagerModeMustBeEnabled {
            get {
                return ResourceManager.GetString("WebGrid_PagerModeMustBeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 This property cannot be set after the &quot;WebGrid&quot; object has been sorted or paged. Make sure that this property is set prior to invoking the &quot;Rows&quot; property directly or indirectly through other methods such as &quot;GetHtml&quot;, &quot;Pager&quot;, &quot;Table&quot;, etc. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_PropertySetterNotSupportedAfterDataBound {
            get {
                return ResourceManager.GetString("WebGrid_PropertySetterNotSupportedAfterDataBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 A value for &quot;rowCount&quot; must be specified when &quot;autoSortAndPage&quot; is set to true and paging is enabled. 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_RowCountNotSpecified {
            get {
                return ResourceManager.GetString("WebGrid_RowCountNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Select 类似的本地化字符串。
        /// </summary>
        public static string WebGrid_SelectLinkText {
            get {
                return ResourceManager.GetString("WebGrid_SelectLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The &quot;fontColor&quot; value is invalid. Valid values are names like &quot;White&quot;, &quot;Black&quot;, or &quot;DarkBlue&quot;, or hexadecimal values in the form &quot;#RRGGBB&quot; or &quot;#RGB&quot;. 类似的本地化字符串。
        /// </summary>
        public static string WebImage_IncorrectColorName {
            get {
                return ResourceManager.GetString("WebImage_IncorrectColorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The &quot;fontFamily&quot; value is invalid. Valid values are font family names like: &quot;Arial&quot;, &quot;Times New Roman&quot;, etc. Make sure that the font family you are trying to use is installed on the server. 类似的本地化字符串。
        /// </summary>
        public static string WebImage_IncorrectFontFamily {
            get {
                return ResourceManager.GetString("WebImage_IncorrectFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The &quot;fontStyle&quot; value is invalid. Valid values are: &quot;Regular&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, and &quot;Strikeout&quot;. 类似的本地化字符串。
        /// </summary>
        public static string WebImage_IncorrectFontStyle {
            get {
                return ResourceManager.GetString("WebImage_IncorrectFontStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The &quot;horizontalAlign&quot; value is invalid. Valid values are: &quot;Right&quot;, &quot;Left&quot;, and &quot;Center&quot;. 类似的本地化字符串。
        /// </summary>
        public static string WebImage_IncorrectHorizontalAlignment {
            get {
                return ResourceManager.GetString("WebImage_IncorrectHorizontalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The &quot;verticalAlign&quot; value is invalid. Valid values are: &quot;Top&quot;, &quot;Bottom&quot;, and &quot;Middle&quot;. 类似的本地化字符串。
        /// </summary>
        public static string WebImage_IncorrectVerticalAlignment {
            get {
                return ResourceManager.GetString("WebImage_IncorrectVerticalAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 Watermark width and height must both be positive or both be zero. 类似的本地化字符串。
        /// </summary>
        public static string WebImage_IncorrectWidthAndHeight {
            get {
                return ResourceManager.GetString("WebImage_IncorrectWidthAndHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 An image could not be constructed from the content provided. 类似的本地化字符串。
        /// </summary>
        public static string WebImage_InvalidImageContents {
            get {
                return ResourceManager.GetString("WebImage_InvalidImageContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 The &quot;priority&quot; value is invalid. Valid values are &quot;Low&quot;, &quot;Normal&quot; and &quot;High&quot;. 类似的本地化字符串。
        /// </summary>
        public static string WebMail_InvalidPriority {
            get {
                return ResourceManager.GetString("WebMail_InvalidPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 A string in the collection is null or empty. 类似的本地化字符串。
        /// </summary>
        public static string WebMail_ItemInCollectionIsNull {
            get {
                return ResourceManager.GetString("WebMail_ItemInCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 &quot;SmtpServer&quot; was not specified. 类似的本地化字符串。
        /// </summary>
        public static string WebMail_SmtpServerNotSpecified {
            get {
                return ResourceManager.GetString("WebMail_SmtpServerNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    查找与 No &quot;From&quot; email address was specified and a default value could not be assigned. 类似的本地化字符串。
        /// </summary>
        public static string WebMail_UnableToDetermineFrom {
            get {
                return ResourceManager.GetString("WebMail_UnableToDetermineFrom", resourceCulture);
            }
        }
    }
}
